import { SpecItem } from "./servicesData";

export interface ProjectDetail {
  slug: string;
  name: string;
  category: "safety-nets" | "invisible-grills" | "cloth-hangers";
  service: string;
  serviceName: string;
  location: string;
  locationSlug: string;
  date: string; // Will display Content Required From Client
  description: string;
  problem: string;
  solution: string;
  materialsUsed: string[];
  process: string[];
  image: string;
  gallery: string[];
  beforeImage: string;
  afterImage: string;
  specs: SpecItem[];
}

export const projectsData: Record<string, ProjectDetail> = {
  "balcony-safety-nets-adyar": {
    slug: "balcony-safety-nets-adyar",
    name: "Balcony Safety Nets Installation in Adyar Residential Complex",
    category: "safety-nets",
    service: "balcony-safety-nets",
    serviceName: "Balcony Safety Nets",
    location: "Adyar",
    locationSlug: "adyar",
    date: "Content Required From Client",
    description: "Installation of heavy-duty double-locked HDPE safety netting on the 7th and 8th floor balconies of a luxury apartment complex in Adyar.",
    problem: "The client resided on a high-floor apartment in Adyar. Due to open balcony railings, there was an active hazard for children and domestic cats. Pigeons were also nesting on the AC ledge, causing noise and hygiene issues.",
    solution: "JSA Enterprises installed a custom-fit, high-tensile HDPE safety netting barrier across the entire balcony frame. The net was anchored securely into concrete ceilings and walls using stainless steel expansion bolts and border ropes.",
    materialsUsed: [
      "100% UV-Stabilized HDPE Nylon netting",
      "0.8mm mesh border ropes",
      "SS304 wall anchoring brackets",
    ],
    process: [
      "Conducted a free site inspection and measurements of balcony boundaries.",
      "Prepared concrete anchor points and drilled hooks at regular intervals.",
      "Tensioned and tied the HDPE mesh across border ropes.",
      "Conducted load testing on the netting anchors to ensure child-safe tension.",
    ],
    image: "/images/main-images/BalconyNet-1.jpg",
    gallery: [
      "/images/main-images/BalconyNet-1.jpg",
      "/images/main-images/BalconyNetWork-1.jpg",
      "/images/main-images/client-balconynet.jpg",
      "/images/main-images/Safety-Net-Work.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/BalconyNet-1.jpg",
    specs: [
      { label: "Material Used", value: "HDPE Monofilament" },
      { label: "Mesh Diameter", value: "35mm x 35mm" },
      { label: "Tensile Strength", value: "Content Required From Client" },
      { label: "Project Warranty", value: "Content Required From Client" },
    ],
  },
  "balcony-net-work-adyar": {
    slug: "balcony-net-work-adyar",
    name: "Residential Balcony Netting Installation in Adyar",
    category: "safety-nets",
    service: "balcony-safety-nets",
    serviceName: "Balcony Safety Nets",
    location: "Adyar",
    locationSlug: "adyar",
    date: "Content Required From Client",
    description: "Complete apartment balcony safety net fitting for child and pet protection.",
    problem: "Open high-rise balcony created safety concerns for young children.",
    solution: "Installed UV-resistant HDPE safety netting tightly anchored with stainless steel hooks.",
    materialsUsed: ["HDPE Copolymer Nylon", "SS304 Anchors", "Border Tension Cord"],
    process: [
      "Site measurement & anchor point layout",
      "Drilling concrete ceiling and sidewalls",
      "Net tensioning and border locking",
    ],
    image: "/images/main-images/BalconyNetWork-1.jpg",
    gallery: [
      "/images/main-images/BalconyNetWork-1.jpg",
      "/images/main-images/BalconyNet-1.jpg",
      "/images/main-images/client-balconynet.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/BalconyNetWork-1.jpg",
    specs: [
      { label: "Material", value: "UV Nylon" },
      { label: "Anchors", value: "SS Expansion Hooks" },
    ],
  },
  "client-balcony-net-tnagar": {
    slug: "client-balcony-net-tnagar",
    name: "Apartment Balcony Safety Netting in T. Nagar",
    category: "safety-nets",
    service: "balcony-safety-nets",
    serviceName: "Balcony Safety Nets",
    location: "T. Nagar",
    locationSlug: "t-nagar",
    date: "Content Required From Client",
    description: "Balcony safety net enclosure for an apartment building in T. Nagar.",
    problem: "Intruding pigeons and safety hazards on open balcony railings.",
    solution: "Fitted translucent monofilament safety net across balcony perimeter.",
    materialsUsed: ["Monofilament Copolymer Net", "SS Eyelets"],
    process: ["Custom net sizing", "Perimeter anchor drilling", "Final load test"],
    image: "/images/main-images/client-balconynet.jpg",
    gallery: [
      "/images/main-images/client-balconynet.jpg",
      "/images/main-images/BalconyNet-1.jpg",
      "/images/main-images/BalconyNetWork-1.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/client-balconynet.jpg",
    specs: [
      { label: "Material", value: "Translucent Copolymer" },
      { label: "Mount Type", value: "Ceiling & Railing" },
    ],
  },
  "invisible-grills-omr": {
    slug: "invisible-grills-omr",
    name: "Window and Balcony Invisible Grills in OMR High-Rise Apartment",
    category: "invisible-grills",
    service: "balcony-invisible-grills",
    serviceName: "Balcony Invisible Grills",
    location: "OMR (Old Mahabalipuram Rd)",
    locationSlug: "omr",
    date: "Content Required From Client",
    description: "Elegant invisible steel wire grill installation along balcony railings of a high-rise IT corridor apartment on OMR.",
    problem: "The resident of a 14th-floor OMR apartment wanted to secure their balcony for pet safety. Traditional heavy iron grills blocked the view and clashed with the modern glass facade of the building.",
    solution: "JSA installed SS316 marine-grade invisible steel wire grills spaced 3 inches apart. The wires are wrapped in a clear nylon sleeve to prevent scratches, clamped firmly in heavy aluminium base tracking.",
    materialsUsed: [
      "SS316 Stainless Steel wire core",
      "High-elastic Nylon protective sheath",
      "Heavy-duty Aluminium track clamps",
    ],
    process: [
      "Mapped and measured the balcony railing profile.",
      "Mounted the heavy aluminium tracking rails at the ceiling and floor base.",
      "Threaded and tensioned the SS316 cables through tracking guides.",
      "Locked the cables at high tension using internal copper sleeves.",
    ],
    image: "/images/main-images/Balcony-Grills.jpg",
    gallery: [
      "/images/main-images/Balcony-Grills.jpg",
      "/images/main-images/Balcony-Grills-2.jpg",
      "/images/main-images/Balcony-Grills-3.jpg",
      "/images/main-images/Balcony-Grills-4.jpg",
      "/images/main-images/Balcony-grill-work.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Balcony-Grills.jpg",
    specs: [
      { label: "Grill Core", value: "316 Stainless Steel" },
      { label: "Spacing", value: "3 inches (75mm)" },
      { label: "Cable Diameter", value: "2.5mm" },
      { label: "Strength Rating", value: "Content Required From Client" },
    ],
  },
  "balcony-grill-work-ecr": {
    slug: "balcony-grill-work-ecr",
    name: "High-Rise Villa Balcony Invisible Grill Setup in ECR",
    category: "invisible-grills",
    service: "balcony-invisible-grills",
    serviceName: "Balcony Invisible Grills",
    location: "ECR",
    locationSlug: "ecr",
    date: "Content Required From Client",
    description: "Premium SS316 invisible steel grill installation along sea-facing villa balconies on ECR.",
    problem: "Corrosion from salt air destroyed old iron grills.",
    solution: "Fitted rustproof marine-grade SS316 cables wrapped in clear protective nylon sheath.",
    materialsUsed: ["Marine SS316 Wires", "Anodized Aluminum Tracks"],
    process: ["Track mounting", "Wire tensioning", "Pressure testing"],
    image: "/images/main-images/Balcony-grill-work.jpg",
    gallery: [
      "/images/main-images/Balcony-grill-work.jpg",
      "/images/main-images/Balcony-Grills-2.jpg",
      "/images/main-images/Balcony-Grills-3.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Balcony-grill-work.jpg",
    specs: [
      { label: "Grade", value: "SS316 Marine Grade" },
      { label: "Coating", value: "Clear Nylon" },
    ],
  },
  "balcony-grills-annanagar": {
    slug: "balcony-grills-annanagar",
    name: "Balcony Invisible Steel Grill Installation in Anna Nagar",
    category: "invisible-grills",
    service: "balcony-invisible-grills",
    serviceName: "Balcony Invisible Grills",
    location: "Anna Nagar",
    locationSlug: "anna-nagar",
    date: "Content Required From Client",
    description: "Modern invisible balcony grill setup for a luxury residential flat in Anna Nagar.",
    problem: "Child safety concerns on high-floor balcony.",
    solution: "Installed vertical SS316 invisible safety wires with 3-inch gap.",
    materialsUsed: ["SS316 Cable", "Aluminum Track"],
    process: ["Base rail installation", "Wire threading and locking"],
    image: "/images/main-images/Balcony-Grills-2.jpg",
    gallery: [
      "/images/main-images/Balcony-Grills-2.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/main-images/Balcony-Grills-3.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Balcony-Grills-2.jpg",
    specs: [
      { label: "Material", value: "SS316 Wires" },
      { label: "Spacing", value: "3 Inches" },
    ],
  },
  "balcony-grills-velachery": {
    slug: "balcony-grills-velachery",
    name: "Apartment Balcony Invisible Safety Grill in Velachery",
    category: "invisible-grills",
    service: "balcony-invisible-grills",
    serviceName: "Balcony Invisible Grills",
    location: "Velachery",
    locationSlug: "velachery",
    date: "Content Required From Client",
    description: "High-tension SS316 invisible wire grill setup on balcony railings.",
    problem: "Pet dog slipping through balcony railing gaps.",
    solution: "Fitted 2-inch spaced invisible wire system.",
    materialsUsed: ["SS316 Stainless Wires", "Coated Tracking"],
    process: ["Measurement", "Frame mounting", "Wire tensioning"],
    image: "/images/main-images/Balcony-Grills-3.jpg",
    gallery: [
      "/images/main-images/Balcony-Grills-3.jpg",
      "/images/main-images/Balcony-Grills-4.jpg",
      "/images/main-images/Balcony-Grills.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Balcony-Grills-3.jpg",
    specs: [{ label: "Gap", value: "2 Inches" }],
  },
  "balcony-grills-porur": {
    slug: "balcony-grills-porur",
    name: "Modern Balcony Safety Steel Grill Project in Porur",
    category: "invisible-grills",
    service: "balcony-invisible-grills",
    serviceName: "Balcony Invisible Grills",
    location: "Porur",
    locationSlug: "porur",
    date: "Content Required From Client",
    description: "High-grade SS316 steel wire invisible grills for apartment balcony.",
    problem: "Safety risks on open 9th-floor balcony.",
    solution: "Secure invisible grill installation with zero view blockage.",
    materialsUsed: ["SS316 Wire", "Aluminum Track"],
    process: ["Structural inspection", "Anchoring & Tensioning"],
    image: "/images/main-images/Balcony-Grills-4.jpg",
    gallery: [
      "/images/main-images/Balcony-Grills-4.jpg",
      "/images/main-images/Balcony-Grills.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Balcony-Grills-4.jpg",
    specs: [{ label: "Core", value: "SS316" }],
  },
  "window-grills-ecr": {
    slug: "window-grills-ecr",
    name: "Villa Window Safety Steel Grill Installation on ECR",
    category: "invisible-grills",
    service: "window-invisible-grills",
    serviceName: "Window Invisible Grills",
    location: "ECR",
    locationSlug: "ecr",
    date: "Content Required From Client",
    description: "Modern invisible steel grills installed across all villa bedroom windows.",
    problem: "Old iron window grates were rusting and blocking natural light.",
    solution: "Replaced with slim SS316 invisible steel wire window grills.",
    materialsUsed: ["SS316 Stainless Wires", "Extruded Aluminum Frame"],
    process: ["Removal of iron grates", "Aluminum frame mounting", "Cable threading"],
    image: "/images/main-images/Window-Grills.jpg",
    gallery: [
      "/images/main-images/Window-Grills.jpg",
      "/images/main-images/Window-Grills-2.jpg",
      "/images/main-images/client-grill-1.jpg",
      "/images/main-images/Grills-Work.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Window-Grills.jpg",
    specs: [
      { label: "Wire Core", value: "SS316 Steel" },
      { label: "Coating", value: "Anti-Scratch Nylon" },
    ],
  },
  "client-grill-tambaram": {
    slug: "client-grill-tambaram",
    name: "Client Residence Window Grill Installation in Tambaram",
    category: "invisible-grills",
    service: "window-invisible-grills",
    serviceName: "Window Invisible Grills",
    location: "Tambaram",
    locationSlug: "tambaram",
    date: "Content Required From Client",
    description: "Window safety grill fitting for a residential home in Tambaram.",
    problem: "Child fall hazard from second-floor bedroom windows.",
    solution: "Installed sleek vertical SS316 wire window invisible grills.",
    materialsUsed: ["SS316 Cable", "Aluminum Base Tracks"],
    process: ["Window casing measurement", "Anchor placement", "Tensioning"],
    image: "/images/main-images/client-grill-1.jpg",
    gallery: [
      "/images/main-images/client-grill-1.jpg",
      "/images/main-images/Window-Grills.jpg",
      "/images/main-images/Window-Grills-2.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/client-grill-1.jpg",
    specs: [{ label: "Material", value: "SS316" }],
  },
  "custom-grills-work-sholinganallur": {
    slug: "custom-grills-work-sholinganallur",
    name: "Custom Stainless Steel Invisible Grill Fitting in Sholinganallur",
    category: "invisible-grills",
    service: "balcony-invisible-grills",
    serviceName: "Balcony Invisible Grills",
    location: "Sholinganallur",
    locationSlug: "sholinganallur",
    date: "Content Required From Client",
    description: "Custom balcony and window invisible grill project in IT corridor flat.",
    problem: "High wind exposure and fall risks on 11th floor.",
    solution: "Heavy-duty SS316 cables tensioned with high-load lockers.",
    materialsUsed: ["SS316 Wires", "Aluminum Rails"],
    process: ["Site check", "Tracking installation", "Wire tensioning & test"],
    image: "/images/main-images/Grills-Work.jpg",
    gallery: [
      "/images/main-images/Grills-Work.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/main-images/Window-Grills.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Grills-Work.jpg",
    specs: [{ label: "Tensile Strength", value: "High Tensile SS316" }],
  },
  "duct-area-nungambakkam": {
    slug: "duct-area-nungambakkam",
    name: "Commercial Building Duct Area Safety Netting in Nungambakkam",
    category: "safety-nets",
    service: "duct-area-safety-nets",
    serviceName: "Duct Area Safety Nets",
    location: "Nungambakkam",
    locationSlug: "nungambakkam",
    date: "Content Required From Client",
    description: "Multi-story ventilation shaft netting to stop bird entry and waste build-up.",
    problem: "Pigeons roosting inside building duct lines causing stench and disease risk.",
    solution: "Sealed duct boundaries with UV-treated monofilament net.",
    materialsUsed: ["Monofilament HDPE Net", "SS Expansion Anchors"],
    process: ["High-rise rope access", "Perimeter hook installation", "Net mounting"],
    image: "/images/main-images/Duct-Area-1.jpg",
    gallery: [
      "/images/main-images/Duct-Area-1.jpg",
      "/images/main-images/Duct-Area-2.jpg",
      "/images/main-images/Duct-Area-3.jpg",
      "/images/main-images/Duct-Area-4.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Duct-Area-1.jpg",
    specs: [{ label: "Shaft Coverage", value: "Full Vertical Enclosure" }],
  },
  "duct-area-guindy": {
    slug: "duct-area-guindy",
    name: "Apartment Duct Shaft Safety Netting Enclosure in Guindy",
    category: "safety-nets",
    service: "duct-area-safety-nets",
    serviceName: "Duct Area Safety Nets",
    location: "Guindy",
    locationSlug: "guindy",
    date: "Content Required From Client",
    description: "Protection netting across open air shafts in a multi-family apartment.",
    problem: "Debris falling down open ventilation shaft into lower floor apartments.",
    solution: "Fitted heavy-duty UV-stabilized shaft safety net.",
    materialsUsed: ["HDPE Safety Netting", "Steel Anchors"],
    process: ["Measurement", "Wall drilling", "Tension net fitting"],
    image: "/images/main-images/Duct-Area-2.jpg",
    gallery: [
      "/images/main-images/Duct-Area-2.jpg",
      "/images/main-images/Duct-Area-1.jpg",
      "/images/main-images/Duct-Area-3.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Duct-Area-2.jpg",
    specs: [{ label: "Material", value: "HDPE Copolymer" }],
  },
  "duct-area-perungudi": {
    slug: "duct-area-perungudi",
    name: "Multi-Story Ventilation Duct Safety Enclosure in Perungudi",
    category: "safety-nets",
    service: "duct-area-safety-nets",
    serviceName: "Duct Area Safety Nets",
    location: "Perungudi",
    locationSlug: "perungudi",
    date: "Content Required From Client",
    description: "Ventilation shaft netting installation for high-rise apartment complex.",
    problem: "Severe pigeon infestation inside open air duct.",
    solution: "Complete shaft sealing with translucent monofilament netting.",
    materialsUsed: ["UV Copolymer Net", "Stainless Steel Eyelets"],
    process: ["Rope access installation", "Perimeter lock"],
    image: "/images/main-images/Duct-Area-3.jpg",
    gallery: [
      "/images/main-images/Duct-Area-3.jpg",
      "/images/main-images/Duct-Area-4.jpg",
      "/images/main-images/Duct-Area-1.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Duct-Area-3.jpg",
    specs: [{ label: "Type", value: "Pigeon Exclusion Shaft Net" }],
  },
  "safety-net-work-medavakkam": {
    slug: "safety-net-work-medavakkam",
    name: "Comprehensive Residential Safety Net Fitting in Medavakkam",
    category: "safety-nets",
    service: "balcony-safety-nets",
    serviceName: "Balcony Safety Nets",
    location: "Medavakkam",
    locationSlug: "medavakkam",
    date: "Content Required From Client",
    description: "Balcony, window, and staircase safety net installation for family residence.",
    problem: "Active toddlers needing complete home fall protection.",
    solution: "Fitted high-impact HDPE safety nets across balconies and open windows.",
    materialsUsed: ["HDPE Copolymer Nylon", "SS304 Brackets"],
    process: ["Whole home measurement", "Anchor drilling & Net tensioning"],
    image: "/images/main-images/Safety-Net-Work.jpg",
    gallery: [
      "/images/main-images/Safety-Net-Work.jpg",
      "/images/main-images/BalconyNet-1.jpg",
      "/images/main-images/Children-Safety-Net.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Safety-Net-Work.jpg",
    specs: [{ label: "Scope", value: "Full Balcony & Window Package" }],
  },
  "sports-net-perungudi": {
    slug: "sports-net-perungudi",
    name: "Turf Cricket Practice Net Enclosure in Perungudi",
    category: "safety-nets",
    service: "sports-nets",
    serviceName: "Sports Nets",
    location: "Perungudi",
    locationSlug: "perungudi",
    date: "Content Required From Client",
    description: "High-impact cricket practice net enclosure for a commercial sports turf.",
    problem: "Cricket balls flying into adjacent residential properties.",
    solution: "Installed heavy-duty 3mm braided nylon sports boundary nets on steel frame.",
    materialsUsed: ["Braided Nylon Cord", "Galvanized Steel Frame Support"],
    process: ["Frame setup", "Net mounting and boundary tensioning"],
    image: "/images/main-images/Sports-Net-1.jpg",
    gallery: [
      "/images/main-images/Sports-Net-1.jpg",
      "/images/main-images/Sports-Net-2.jpg",
      "/images/main-images/Sports-Nets-3.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Sports-Net-1.jpg",
    specs: [{ label: "Cord", value: "3.0mm Braided Nylon" }],
  },
  "sports-net-navalur": {
    slug: "sports-net-navalur",
    name: "Multi-Sport Arena Boundary Netting in Navalur",
    category: "safety-nets",
    service: "sports-nets",
    serviceName: "Sports Nets",
    location: "Navalur",
    locationSlug: "navalur",
    date: "Content Required From Client",
    description: "30ft height sports net boundary for football and cricket grounds.",
    problem: "High velocity ball impacts damaging surrounding fence structures.",
    solution: "Fitted shock-absorbing UV-treated braided sports netting.",
    materialsUsed: ["UV Braided Nylon Twine", "Steel Boundary Cable"],
    process: ["Poles erection", "High tension cable stringing", "Net hookup"],
    image: "/images/main-images/Sports-Nets-3.jpg",
    gallery: [
      "/images/main-images/Sports-Nets-3.jpg",
      "/images/main-images/Sports-Net-1.jpg",
      "/images/main-images/Sports-Net-2.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Sports-Nets-3.jpg",
    specs: [{ label: "Height", value: "30 Feet" }],
  },
  "ceiling-hangers-velachery": {
    slug: "ceiling-hangers-velachery",
    name: "Ceiling-Mounted Pulley Cloth Hanger Setup in Velachery Flat",
    category: "cloth-hangers",
    service: "ceiling-cloth-hangers",
    serviceName: "Ceiling Cloth Hangers",
    location: "Velachery",
    locationSlug: "velachery",
    date: "Content Required From Client",
    description: "Installation of a 6-pipe dual-rope pulley ceiling drying hanger in a compact utility balcony of a Velachery residence.",
    problem: "The resident faced severe drying space constraints. Standard metal floor racks blocked the utility balcony, restricting access to the washing machine and blocking ventilation.",
    solution: "JSA installed a premium ceiling-mounted pulley cloth drying system with 6 rustproof stainless steel pipes, allowing the resident to lift damp clothes easily to ceiling height.",
    materialsUsed: [
      "SS304 rustproof stainless steel rods",
      "Braided high-strength nylon ropes",
      "Dual rope pulley lockers & rollers",
    ],
    process: [
      "Inspected ceiling structure to confirm secure anchoring spots.",
      "Drilled and mounted pulley pulleys into concrete ceiling.",
      "Threaded the braided nylon cords and locked SS304 rods in place.",
      "Tested vertical lift weight limit (up to 15kg per rod).",
    ],
    image: "/images/main-images/Cloth-Hangera-1.jpg",
    gallery: [
      "/images/main-images/Cloth-Hangera-1.jpg",
      "/images/hero/cloth-hanger.png",
      "/images/hero/cloth-hanger1.jpg",
    ],
    beforeImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    afterImage: "/images/main-images/Cloth-Hangera-1.jpg",
    specs: [
      { label: "Rod Count", value: "6 Pipes" },
      { label: "Rod Length", value: "6 feet (SS304)" },
      { label: "Rope material", value: "Braided Nylon cord" },
      { label: "Warranty", value: "Content Required From Client" },
    ],
  },
};


